export const redirectUrlMapper = {
  '/posts/activity/bali-remote': '/post/bali-remote-work',
  '/posts/activity/geultto8-seminar': '/post/geultto8-open-source-seminar',
  '/posts/book/micro-state-management': '/post/micro-state-management-review',
  '/posts/book/woowa-type': '/post/woowa-type-review',
  '/posts/book/quality-of-job': '/post/quality-of-job-review',
  '/posts/js/mdn-ko-reviewer': '/post/mdn-ko-organizer',
  '/posts/js/dev-server': '/post/vite-dev-server',
  '/posts/js/sort': '/post/array-prototype-sort',
  '/posts/js/use-transition': '/post/use-transition',
  '/posts/js/use-prevent-leave': '/post/use-prevent-leave',
  '/posts/js/storybook7': '/post/storybook7',
  '/posts/js/typescript5': '/post/typescript5',
  '/posts/js/renovate': '/post/renovate',
  '/posts/js/turborepo': '/post/turborepo',
  '/posts/tool/mac/init': '/post/mac-init-apps',
};
