name: netlify-preview

runs:
  using: composite

  steps:
    # https://cli.netlify.com/
    - name: Netlify deploy
      id: netlify-deploy
      shell: bash
      run: |
        pnpm nf \
          --dir out \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_API_TOKEN }} \
          --json \
          > deploy_output.json

    - name: Generate URL Preview
      id: url-preview
      if: ${{ env.BRANCH_NAME == 'main' }}
      run: |
        NETLIFY_PREVIEW_URL=$(jq -r '.deploy_url' deploy_output.json)
        echo "NETLIFY_PREVIEW_URL=$NETLIFY_PREVIEW_URL" >> "$GITHUB_OUTPUT"

    - name: Comment URL Preview on PR
      uses: actions/github-script@v7
      if: ${{ env.BRANCH_NAME == 'main' }}
      env:
        NETLIFY_PREVIEW_URL: ${{ steps.url-preview.outputs.NETLIFY_PREVIEW_URL }}
      with:
        script: |
          async function comment(){
            const result = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            })
            const issueNumber = result.data[0].number
            if(issueNumber){
              await github.rest.issues.createComment({
                issue_number: issueNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Preview URL: ' + process.env.NETLIFY_PREVIEW_URL
              })
            }else{
              console.log('No PR found for commit ' + context.sha)
            }
          }
          comment()
