/**
 * 예전 parseMDX.ts 에서 사용하던 방식
 * const module = await import(`/_posts/${fullSlug}/docs.mdx`);
 *
 * Turbopack은 이 패턴을 지원하지 않음. Webpack은 /_posts/를 프로젝트 루트로 resolve하고 런타임에 동적으로 모듈을 로드했지만, Turbopack(Rust
 * 기반)은 빌드 시점에 모든 import를 정적으로 분석해야 함. 변수가 포함된 경로는 어떤 파일이 필요한지 알 수 없으므로 실패함.
 *
 * 따라서, pre-scripts.ts 에서 mdxMap.ts 를 생성하여 사용해야 함.
 */
// Auto-generated by pre-scripts.ts — do not edit manually
import * as _0 from '_posts/activity/2024-woowa-ignite/docs.mdx';
import * as _1 from '_posts/activity/geultto8-open-source-seminar/docs.mdx';
import * as _2 from '_posts/activity/inflearn-meetup-03-dev-career/docs.mdx';
import * as _3 from '_posts/activity/junction2023/docs.mdx';
import * as _4 from '_posts/book/micro-state-management-review/docs.mdx';
import * as _5 from '_posts/book/proving-ground-review/docs.mdx';
import * as _6 from '_posts/book/quality-of-job-review/docs.mdx';
import * as _7 from '_posts/book/woowa-type-review/docs.mdx';
import * as _8 from '_posts/js/array-prototype-sort/docs.mdx';
import * as _9 from '_posts/js/deploy-eslint-plugin/docs.mdx';
import * as _10 from '_posts/js/google-adsense/docs.mdx';
import * as _11 from '_posts/js/implicit-coercion/docs.mdx';
import * as _12 from '_posts/js/is-supply-chain-attack/docs.mdx';
import * as _13 from '_posts/js/n-api/docs.mdx';
import * as _14 from '_posts/js/nodejs-architecture-dive/docs.mdx';
import * as _15 from '_posts/js/object-type/docs.mdx';
import * as _16 from '_posts/js/prettier3/docs.mdx';
import * as _17 from '_posts/js/renovate/docs.mdx';
import * as _18 from '_posts/js/storybook7/docs.mdx';
import * as _19 from '_posts/js/turborepo/docs.mdx';
import * as _20 from '_posts/js/typescript-subtyping/docs.mdx';
import * as _21 from '_posts/js/typescript5/docs.mdx';
import * as _22 from '_posts/js/use-prevent-leave/docs.mdx';
import * as _23 from '_posts/js/use-transition/docs.mdx';
import * as _24 from '_posts/js/visual-regression-test/docs.mdx';
import * as _25 from '_posts/js/vite-dev-server/docs.mdx';
import * as _26 from '_posts/retrospect/2023/docs.mdx';
import * as _27 from '_posts/rust/udemy-rust-programming/docs.mdx';
import * as _28 from '_posts/tool/mac-init-apps/docs.mdx';
import * as _29 from '_posts/activity/mdn/mdn-contributing-translations/docs.mdx';
import * as _30 from '_posts/activity/mdn/mdn-ko-organizer/docs.mdx';
import * as _31 from '_posts/activity/remote-work/bali-remote-work/docs.mdx';
import * as _32 from '_posts/activity/remote-work/jeju-remote-work/docs.mdx';
import * as _33 from '_posts/algorithm/goorm/goorm-195687/docs.mdx';
import * as _34 from '_posts/algorithm/goorm/goorm-195692/docs.mdx';
import * as _35 from '_posts/algorithm/goorm/goorm-195693/docs.mdx';
import * as _36 from '_posts/algorithm/goorm/goorm-195696/docs.mdx';
import * as _37 from '_posts/algorithm/goorm/goorm-195698/docs.mdx';
import * as _38 from '_posts/algorithm/leetcode/easy/leetcode-easy-2727/docs.mdx';
import * as _39 from '_posts/algorithm/leetcode/hard/leetcode-hard-42/docs.mdx';
import * as _40 from '_posts/algorithm/leetcode/medium/leetcode-medium-238/docs.mdx';

export const mdxMap: Record<string, unknown> = {
  'activity/2024-woowa-ignite': _0,
  'activity/geultto8-open-source-seminar': _1,
  'activity/inflearn-meetup-03-dev-career': _2,
  'activity/junction2023': _3,
  'book/micro-state-management-review': _4,
  'book/proving-ground-review': _5,
  'book/quality-of-job-review': _6,
  'book/woowa-type-review': _7,
  'js/array-prototype-sort': _8,
  'js/deploy-eslint-plugin': _9,
  'js/google-adsense': _10,
  'js/implicit-coercion': _11,
  'js/is-supply-chain-attack': _12,
  'js/n-api': _13,
  'js/nodejs-architecture-dive': _14,
  'js/object-type': _15,
  'js/prettier3': _16,
  'js/renovate': _17,
  'js/storybook7': _18,
  'js/turborepo': _19,
  'js/typescript-subtyping': _20,
  'js/typescript5': _21,
  'js/use-prevent-leave': _22,
  'js/use-transition': _23,
  'js/visual-regression-test': _24,
  'js/vite-dev-server': _25,
  'retrospect/2023': _26,
  'rust/udemy-rust-programming': _27,
  'tool/mac-init-apps': _28,
  'activity/mdn/mdn-contributing-translations': _29,
  'activity/mdn/mdn-ko-organizer': _30,
  'activity/remote-work/bali-remote-work': _31,
  'activity/remote-work/jeju-remote-work': _32,
  'algorithm/goorm/goorm-195687': _33,
  'algorithm/goorm/goorm-195692': _34,
  'algorithm/goorm/goorm-195693': _35,
  'algorithm/goorm/goorm-195696': _36,
  'algorithm/goorm/goorm-195698': _37,
  'algorithm/leetcode/easy/leetcode-easy-2727': _38,
  'algorithm/leetcode/hard/leetcode-hard-42': _39,
  'algorithm/leetcode/medium/leetcode-medium-238': _40,
};
