import fs from 'fs';
import path from 'path';

const { process, console } = globalThis;

const PUBLIC_PATH = path.join(process.cwd(), 'public/posts');
const POST_PATH = path.join(process.cwd(), '_posts');

const allowFiles = [
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.svg',
  '.webp',
  '.pdf',
  '.mov',
];

const postDirPaths = [
  ...new Set(
    fs
      .readdirSync(POST_PATH, {
        withFileTypes: true,
        recursive: true,
      })
      .filter((post) => post.isFile())
      // _posts 이후의 경로만 추출
      .map((post) => post.parentPath.slice(POST_PATH.length + 1)),
  ),
];

const assetsToPublic = async () => {
  for await (const postDirPath of postDirPaths) {
    const postUrl = postDirPath.split('/').pop();
    if (!postUrl) continue;
    const publicPostPath = path.resolve(PUBLIC_PATH, postUrl);
    const postDirFullPath = path.resolve(POST_PATH, postDirPath);

    const assetFiles = fs
      .readdirSync(postDirFullPath, {
        withFileTypes: true,
      })
      .filter((file) => allowFiles.includes(path.extname(file.name)))
      .map((file) => file.name);

    if (assetFiles.length === 0) continue;

    if (fs.existsSync(publicPostPath)) {
      fs.rmSync(publicPostPath, { recursive: true });
    }
    fs.mkdirSync(publicPostPath, { recursive: true });

    await Promise.all(
      assetFiles.map(async (file) => {
        const assetPath = path.resolve(postDirFullPath, file);
        const movePath = path.resolve(publicPostPath, file);
        await fs.promises.copyFile(assetPath, movePath);
      }),
    );
  }
};

const main = async () => {
  await assetsToPublic();
  console.info('\n\x1b[36m ✓ Assets moved to public\x1b[0m');
  generateMdxMap();
  console.info('\x1b[36m ✓ MDX import map generated\x1b[0m\n');
};

const generateMdxMap = () => {
  const mdxSlugs = postDirPaths.filter((dirPath) => {
    const fullPath = path.resolve(POST_PATH, dirPath, 'docs.mdx');
    return fs.existsSync(fullPath);
  });

  const imports = mdxSlugs
    .map((slug, i) => `import * as _${i} from '_posts/${slug}/docs.mdx';`)
    .join('\n');

  const entries = mdxSlugs.map((slug, i) => `  '${slug}': _${i},`).join('\n');

  const content = `/**
 * 예전 parseMDX.ts 에서 사용하던 방식
 * const module = await import(\`/_posts/\${fullSlug}/docs.mdx\`);
 *
 * Turbopack은 이 패턴을 지원하지 않음. Webpack은 /_posts/를 프로젝트 루트로 resolve하고 런타임에 동적으로 모듈을 로드했지만, Turbopack(Rust
 * 기반)은 빌드 시점에 모든 import를 정적으로 분석해야 함. 변수가 포함된 경로는 어떤 파일이 필요한지 알 수 없으므로 실패함.
 *
 * 따라서, pre-scripts.ts 에서 mdxMap.ts 를 생성하여 사용해야 함.
 */
// Auto-generated by pre-scripts.ts — do not edit manually
${imports}

export const mdxMap: Record<string, unknown> = {
${entries}
};
`;

  const outPath = path.join(
    process.cwd(),
    'src/features/shared/helpers/mdx/mdxMap.ts',
  );
  fs.writeFileSync(outPath, content);
};

await main();
