name: code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  pull-requests: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🌱 Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: 🏁 Lint
        run: pnpm lint

      - name: 🪤 Jest
        run: pnpm jest

  build-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🌱 Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: 🏗 Build and Export
        uses: ./.github/actions/nextjs-build-export
