name: e2e

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🌱 Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: 🏗 Build and Export
        uses: ./.github/actions/nextjs-build-export
        with:
          e2e: 'true'

      - name: 📦 Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: e2e-build
          path: out/
          retention-days: 1

  others:
    needs: build
    uses: './.github/workflows/e2e-reusable.yml'
    with:
      others: true

  dom-snapshot:
    needs: build
    uses: './.github/workflows/e2e-reusable.yml'
    with:
      dom-snapshot: true

  screen-snapshot:
    needs: build
    uses: './.github/workflows/e2e-reusable.yml'
    with:
      screen-snapshot: true
