name: PR Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    uses: './.github/workflows/resuable.yml'

  lint:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: './.github/workflows/resuable.yml'
      - run: pnpm lint

  build-export:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: './.github/workflows/resuable.yml'
      - run: pnpm deploy-blog
